version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ecommerce
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecomuser
      MYSQL_PASSWORD: ecompass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: achiaravallidocker/ecommerce-backend:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: ecomuser
      SPRING_DATASOURCE_PASSWORD: ecompass

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: achiaravallidocker/ecommerce-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:8080/api

volumes:
  mysql_data:
