version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ecommerce
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecomuser
      MYSQL_PASSWORD: ecompass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
